name:   Deploy website
on:
  workflow_dispatch:
  push:
    branches: 
      - master
jobs :
  test:
      runs-on:
      steps:
         - name : Get code
           uses: action/checkout@v3
         - name : Install dependencies
           run: npm ci
         - name : Lint code
           run : npm run lint
         - name: npm run test
      build:
       needs: test
       runs-on: ubuntu-latest
       steps :
            - name: Get code
              uses: action/checkout@v3
            - name : Install dependencies
              run: npm ci
            - name : Build website
              run : npm run lint
      deploy:
        needs: build
        runs-on: ubuntu-leatest
        steps:
           - name: Deploy
             run : echo "Deploy"


                 
